name: Giovanni Calixte's Portfolio
title: Giovanni's Portfolio
description: 
tags:
  - blog
  - portfolio
  - data
  - analytics

show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /About
  - title: Collegiate Work
    url: /CollegeWork
  - title: Projects
    url: /Projects

email: giovannicalixte1@gmail.com
# See: https://disqus.com/
# disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
# formspree_form_id: formspree_form_id
