# Site Settings
name: Giovanni Calixte's Portfolio
title: Giovanni's Portfolio
description: 
tags:
  - blog
  - portfolio
  - data
  - analytics

show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /About
  - title: Collegiate Work
    url: /CollegeWork
  - title: Projects
    url: /Projects

email: giovannicalixte1@gmail.com
# See: https://disqus.com/
# disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
# formspree_form_id: formspree_form_id


# Social Media Settings
# Remove the item if you don't need it
github_username: GcalGit93
#facebook_username: facebook_username
#twitter_username: twitter_username
#instagram_username: instagram_username
linkedin_username: giovanni-calixte
#medium_username: medium_username


# Posts Settings
#show_time_bar: false
#show_modal_on_exit: false
#show_modal_on_finish_post: true
#two_columns_layout: true


# Advanced Settings
baseurl: /gcalgit93 # the subpath of your site, e.g. /blog
url: https://gcalgit93.github.io # the base hostname & protocol for your site
# google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
#sent_message_url: "/contact/message-sent/"


# Build settings
#markdown: kramdown
#highlighter: rouge
#permalink: /:title/
#collections:
#  authors:
#    output: true
#paginate_path: "/page/:num/"
#show_get_theme_btn: true
#use_logo: false

# Content paginator
#paginate_content:
#  enabled: true
#  debug: false
#  collections:
#    - posts
#  auto: false
#  separator: "--page-break--"
#  permalink: "/:num/"
#  seo_canonical: true
#  properties:
#    part:
#      is_generated: true
#    last:
#      is_generated: true
#    single:
#      is_generated: true

# SASS
sass:
  style: compressed

#theme: jekflix
remote_theme: thiagorossener/jekflix-template 

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude my node related stuff
exclude: [
  'docs/',
  'vendor/',
  'LICENSE',
  'CHANGELOG.md',
  'jekflix.gemspec',
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
# version: v3.1.2
